[features]
seeds = false
skip-lint = false
[programs.localnet]
tic_tac_toe = "CQCmh5YYEMjf3CsyBzVzoG5yLbXMvPipBH3a9bMsJ74Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/anonymous/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
